=== flexiblepower/defpi-core/maven-plugin/src/main/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "properties": {
    "name": {
      "$ref": "#/definitions/name"
    },
    "version": {
      "type": "string",
      "pattern": "^([0-9]+\\.)*[0-9]+(-[0-9a-zA-Z]*)?$"
    },
    "parameters": {
      "type": "array",
      "uniqueItems": true,
      "items": {
      	"type": "object",
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^([a-z])([a-zA-Z0-9\\.])*$"
          },
          "name": {
           	"$ref":"#/definitions/name"
          },
          "type": {
            "enum": [
              "boolean",
              "byte",
              "char",
              "short",
              "int",
              "long",
              "float",
              "double",
              "string"
            ]
          },
          "isArray": {
            "type": "boolean" 
          },
          "isOptional": {
            "type": "boolean"
          },
          "values": {
            "type": "array",
            "items": {
              "type": "string",
              "uniqueItems": true,
              "items": {
         	    "type": "string"
              }
            }
          },
          "labels": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string"
            }
          },
          "default": {
            "type": ["string", "number"]
          }
        },
        "required": [
          "id",
          "name",
          "type"
        ],
        "additionalProperties": false
      }
    },
    "interfaces": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "$ref": "#/definitions/name"
          },
          "allowMultiple": {
            "type": "boolean"
          },
          "autoConnect": {
            "type": "boolean"
          },
          "interfaceVersions": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "object",
              "properties": {
                "versionName": {
                  "$ref": "#/definitions/name"
                },
                "type": {
                  "type": "string",
                  "enum": [
                    "xsd",
                    "proto"
                  ]
                },
                "location": {
                  "type": "string"
                },
                "sends": {
                  "$ref": "#/definitions/messageArray"
                },
                "receives": {
                  "$ref": "#/definitions/messageArray"
                }
              },
              "required": [
                "versionName",
                "type",
                "location",
                "sends",
                "receives"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "allowMultiple",
          "autoConnect",
          "name"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "name",
    "version"
  ],
  "additionalProperties": false,
  "definitions": {
    "messageArray": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "name": {
      "type": "string",
      "maxLength": 64,
      "minLength": 1
    }
  }
}

=== flexiblepower/defpi-core/skeleton_xsd/src/main/resources/service.json
{
  "name": "Books library",
  "version": "85",
  "parameters": [ 
  	{ 
  	  "id": "books.frequency",
  	  "name": "frequency",
  	  "type": "double",
  	  "default": "0.1"
  	},
  	{
  	  "id": "books.type",
  	  "name": "type",
  	  "type": "string",
  	  "values": ["historic", "romance", "sci-fi"],
  	  "default": "sci-fi"
  	}
  ],
  "interfaces": [
    {
      "name": "books XSD",
      "autoConnect": false,
      "allowMultiple": false,
      "interfaceVersions": [
        {
          "versionName": "8.5 XSD",
          "type": "xsd",
          "location": "books.xsd",
          "sends": ["BooksForm"],
          "receives": ["BooksForm"]
        },
        {
          "versionName": "readonly",
          "type": "xsd",
          "location": "books.xsd",
          "sends": [],
          "receives": ["BooksForm"]
        }
      ]
    }
  ]
}
